version: '3.8'
services:
    propel-app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        env_file:
           - ./.env
#        entrypoint: sh -c "/tmp/run.sh"
        networks:
            - propel
        depends_on:
            mysql-db:
                condition: service_healthy
    mysql-db:
        platform: linux/x86_64
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_USER: laravel
            MYSQL_DATABASE: propel_project
            MYSQL_PASSWORD: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysqldata:/var/lib/mysql/
        networks:
            - propel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        ports:
            - '3306:3306'

    propel-nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - 80:80
        networks:
            - propel
        volumes:
            - .:/usr/src/app
            - ./docker/nginx/conf:/etc/nginx/conf.d
        depends_on:
            - propel-app
networks:
    propel:
        driver: bridge
volumes:
    mysqldata:
        driver: local
